"use client";

import React, { useState } from "react";
import { SecuritySettings, ActiveSessionItem } from "@/types/settings";
import {
  Shield,
  KeyRound,
  Smartphone,
  Laptop,
  CheckCircle2,
  AlertTriangle,
  History,
  Lock,
  Check,
} from "lucide-react";

interface SecuritySettingsCardProps {
  security: SecuritySettings;
  onUpdate: (updated: Partial<SecuritySettings>) => void;
}

export const SecuritySettingsCard: React.FC<SecuritySettingsCardProps> = ({
  security,
  onUpdate,
}) => {
  const [currentPassword, setCurrentPassword] = useState("");
  const [newPassword, setNewPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [passwordSuccess, setPasswordSuccess] = useState(false);
  const [sessions, setSessions] = useState<ActiveSessionItem[]>(security.activeSessions);

  const handlePasswordSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (newPassword !== confirmPassword) {
      alert("New password and confirm password do not match!");
      return;
    }
    setPasswordSuccess(true);
    setCurrentPassword("");
    setNewPassword("");
    setConfirmPassword("");
    onUpdate({ passwordLastChanged: "Just now" });
    setTimeout(() => setPasswordSuccess(false), 2000);
  };

  const toggle2FA = () => {
    onUpdate({ twoFactorEnabled: !security.twoFactorEnabled });
  };

  const handleRevokeSession = (sessionId: string) => {
    const remaining = sessions.filter((s) => s.id !== sessionId);
    setSessions(remaining);
    onUpdate({ activeSessions: remaining });
  };

  return (
    <div className="rounded-3xl bg-surface border border-border/80 p-6 sm:p-7 shadow-xs space-y-6">
      <div className="flex items-center gap-2.5 pb-4 border-b border-border/80">
        <div className="w-9 h-9 rounded-xl bg-accent/15 text-accent flex items-center justify-center border border-accent/20">
          <Shield className="w-4 h-4" />
        </div>
        <div>
          <h2 className="text-lg font-bold text-ink">Security & Authentication</h2>
          <p className="text-xs text-ink-muted">
            Manage passwords, two-factor authentication, and monitor active sessions.
          </p>
        </div>
      </div>

      {/* Two-Factor Authentication Banner */}
      <div className="p-4 rounded-2xl bg-canvas/70 border border-border/70 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="flex items-start gap-3.5">
          <div className="w-10 h-10 rounded-xl bg-emerald-500/15 text-emerald-500 flex items-center justify-center shrink-0">
            <Smartphone className="w-5 h-5" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h3 className="text-sm font-bold text-ink">Two-Factor Authentication (2FA)</h3>
              {security.twoFactorEnabled ? (
                <span className="inline-flex items-center gap-1 text-[10px] font-bold px-2 py-0.5 rounded-full bg-emerald-500/15 text-emerald-600 dark:text-emerald-400 border border-emerald-500/30">
                  <CheckCircle2 className="w-3 h-3" />
                  Enabled (Authenticator App)
                </span>
              ) : (
                <span className="inline-flex items-center gap-1 text-[10px] font-bold px-2 py-0.5 rounded-full bg-amber-500/15 text-amber-600 dark:text-amber-400 border border-amber-500/30">
                  Disabled
                </span>
              )}
            </div>
            <p className="text-xs text-ink-muted mt-0.5">
              Protect your placement account with time-based OTPs generated by Google Authenticator or 1Password.
            </p>
          </div>
        </div>

        <button
          type="button"
          onClick={toggle2FA}
          className={`px-4 py-2 rounded-xl text-xs font-bold transition-all shrink-0 ${
            security.twoFactorEnabled
              ? "bg-surface border border-border hover:bg-red-500/10 hover:text-red-600 text-ink"
              : "bg-accent text-white hover:bg-accent/90 shadow-sm"
          }`}
        >
          {security.twoFactorEnabled ? "Disable 2FA" : "Enable 2FA"}
        </button>
      </div>

      {/* Change Password Form */}
      <form onSubmit={handlePasswordSubmit} className="space-y-4 pt-2">
        <div className="flex items-center justify-between">
          <h4 className="text-xs font-bold uppercase tracking-wider text-ink flex items-center gap-1.5">
            <KeyRound className="w-3.5 h-3.5 text-accent" />
            Update Account Password
          </h4>
          <span className="text-[11px] text-ink-muted">
            Last updated: {security.passwordLastChanged}
          </span>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
          <div>
            <label className="text-[11px] font-bold uppercase tracking-wider text-ink-muted block mb-1">
              Current Password
            </label>
            <input
              type="password"
              placeholder="••••••••"
              value={currentPassword}
              onChange={(e) => setCurrentPassword(e.target.value)}
              className="w-full px-3.5 py-2 rounded-xl bg-canvas border border-border text-xs text-ink focus:outline-none focus:border-accent"
              required
            />
          </div>

          <div>
            <label className="text-[11px] font-bold uppercase tracking-wider text-ink-muted block mb-1">
              New Password
            </label>
            <input
              type="password"
              placeholder="Minimum 8 characters"
              value={newPassword}
              onChange={(e) => setNewPassword(e.target.value)}
              className="w-full px-3.5 py-2 rounded-xl bg-canvas border border-border text-xs text-ink focus:outline-none focus:border-accent"
              required
            />
          </div>

          <div>
            <label className="text-[11px] font-bold uppercase tracking-wider text-ink-muted block mb-1">
              Confirm New Password
            </label>
            <input
              type="password"
              placeholder="Confirm new password"
              value={confirmPassword}
              onChange={(e) => setConfirmPassword(e.target.value)}
              className="w-full px-3.5 py-2 rounded-xl bg-canvas border border-border text-xs text-ink focus:outline-none focus:border-accent"
              required
            />
          </div>
        </div>

        <div className="flex justify-end">
          <button
            type="submit"
            className="px-4 py-2 rounded-xl bg-accent text-white text-xs font-bold hover:bg-accent/90 transition-all flex items-center gap-1.5 shadow-sm active:scale-95"
          >
            {passwordSuccess ? (
              <>
                <Check className="w-3.5 h-3.5" />
                <span>Password Updated!</span>
              </>
            ) : (
              <span>Change Password</span>
            )}
          </button>
        </div>
      </form>

      {/* Active Sessions */}
      <div className="pt-5 border-t border-border/80 space-y-3">
        <h4 className="text-xs font-bold uppercase tracking-wider text-ink flex items-center gap-1.5">
          <Laptop className="w-3.5 h-3.5 text-accent" />
          Active Login Sessions ({sessions.length})
        </h4>

        <div className="space-y-2.5">
          {sessions.map((sess) => (
            <div
              key={sess.id}
              className="p-3.5 rounded-2xl bg-canvas/70 border border-border/70 flex flex-col sm:flex-row sm:items-center justify-between gap-3"
            >
              <div className="flex items-center gap-3">
                <div className="w-9 h-9 rounded-xl bg-surface border border-border flex items-center justify-center text-ink shrink-0">
                  <Laptop className="w-4 h-4" />
                </div>
                <div>
                  <div className="flex items-center gap-2">
                    <span className="text-xs font-bold text-ink">{sess.device}</span>
                    {sess.isCurrent && (
                      <span className="text-[10px] font-bold px-1.5 py-0.2 rounded bg-accent/15 text-accent border border-accent/25">
                        Current Device
                      </span>
                    )}
                  </div>
                  <p className="text-[11px] text-ink-muted mt-0.5">
                    IP: {sess.ipAddress} • {sess.location} • {sess.lastActive}
                  </p>
                </div>
              </div>

              {!sess.isCurrent && (
                <button
                  type="button"
                  onClick={() => handleRevokeSession(sess.id)}
                  className="px-3 py-1 rounded-lg bg-surface border border-border hover:bg-red-500/10 text-red-600 dark:text-red-400 text-xs font-semibold transition-colors self-end sm:self-center"
                >
                  Revoke
                </button>
              )}
            </div>
          ))}
        </div>
      </div>

      {/* Security Activity Log */}
      <div className="pt-5 border-t border-border/80 space-y-3">
        <h4 className="text-xs font-bold uppercase tracking-wider text-ink flex items-center gap-1.5">
          <History className="w-3.5 h-3.5 text-accent" />
          Recent Security Activity Log
        </h4>

        <div className="space-y-2">
          {security.activityLog.map((log) => (
            <div
              key={log.id}
              className="p-3 rounded-xl bg-canvas/50 border border-border/60 flex items-center justify-between text-xs"
            >
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500 shrink-0" />
                <span className="font-semibold text-ink">{log.event}</span>
                <span className="text-ink-muted text-[11px]">({log.device})</span>
              </div>
              <span className="text-[11px] text-ink-muted">{log.timestamp}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
